
%% CLEAR WORKSPACE AND LOAD DATASET

clc; close all; clear;
system('sudo purge')
cd(fileparts(which('GENOS.m')));
rng('shuffle')

% load('BRADSDATASETV2.mat')

% load('GENOSDATA_ALL_NEW.mat',...
% 'ADMX','SNPCASE','SNPCTRL','PHE','CASEID','CTRLID','CASEMX','CTRLMX','COHORTS')


% load('GENOSDATA_EQUAL_NEW.mat',...
% 'ADMX','SNPCASE','SNPCTRL','PHE','CASEID','CTRLID','CASEMX','CTRLMX','COHORTS')




% THIS IS THE LATEST DATASET. STUDY COHORTS ALL HAVE EQUAL CASE & CTRL N
which('GENOSDATA_ALL_TRIMMED.mat')
load('GENOSDATA_ALL_TRIMMED.mat',...
'ADMX','SNPCASE','SNPCTRL','PHE','CASEID','CTRLID','CASEMX','CTRLMX','COHORTS','CCMX')



% USED DURING TESTING ORIGINAL DATASET FORMAT
% which('GENOSDATA_ALL.mat')
% load('GENOSDATA_ALL.mat')





%% FILTER OUT UNWANTED VARIANTS


% FILTER VARIANTS BASED ON EFFECT TYPE
%------------------------------------------------

%   [SYN MIS STG STL SPA SPD INT NCE UTR CUK]
L = [ 1   1   1   1   1   1   1   1   1   0];

[KEEP] = keepEFFECT(ADMX,L);

ADMX    = ADMX( KEEP , : );
SNPCASE = SNPCASE(KEEP);
SNPCTRL = SNPCTRL(KEEP);
ADMX.VID = ( 1:size(ADMX,1) )';





% FILTER VARIANTS BASED ON LOW ALT COUNTS
%------------------------------------------------

PASS = (ADMX.CASEALTS > 2 & ADMX.CTRLALTS > 2) & ...
       ((ADMX.CASEALTS + ADMX.CTRLALTS)>30);

ADMX    = ADMX( PASS , :);
SNPCASE = SNPCASE(PASS);
SNPCTRL = SNPCTRL(PASS);
ADMX.VID = (1:size(ADMX,1))';





% FILTER VARIANTS WITH MORE ALTS THAN REFS
%------------------------------------------------

PASS = (ADMX.CASEALTS < ADMX.CASEREFS) | (ADMX.CTRLALTS < ADMX.CTRLREFS);
disp(sum(~PASS))

ADMX    = ADMX( PASS , :);
SNPCASE = SNPCASE(PASS);
SNPCTRL = SNPCTRL(PASS);
ADMX.VID = (1:size(ADMX,1))';


clearvars -except ADMX SNPCASE SNPCTRL PHE CASEID CTRLID CASEMX CTRLMX IDVX




%% LOG NORMALIZE FISHERS ODDS RATIO

ADMX.FISHOR  = log(ADMX.FISHOR );
ADMX.FISHORS = log(ADMX.FISHORS);

histogram(ADMX.FISHOR)
histogram(ADMX.FISHORS)


clearvars -except ADMX SNPCASE SNPCTRL PHE CASEID CTRLID CASEMX CTRLMX IDVX

%% CREATE VARIANT SUBSET FOR DETAILED ANALYSES



PASS = ((ADMX.CASEALTS + ADMX.CTRLALTS)>35) ...
        & (ADMX.FISHPS < .01) ...
        & (abs(ADMX.FISHOR) > .2) ...
        & (ADMX.CASEALTS > 2 & ADMX.CTRLALTS > 2);


ASYMX      = ADMX(PASS, :);
ASYCASE    = SNPCASE(PASS);
ASYCTRL    = SNPCTRL(PASS);
ASYMX.VID  = (1:size(ASYMX,1))';



clearvars -except ADMX SNPCASE SNPCTRL PHE CASEID CTRLID CASEMX CTRLMX IDVX ...
ASYMX ASYCASE ASYCTRL



%% ONLY KEEP ONE VARIANT INSTANCE PER GENE (THE ONE WITH LOWEST P-VAL)

% SORT DATASET FROM LOW TO HIGH FISHERS P-VALUE
% UNIQUE() WILL RETURN INDEX OF VARIANT WITH LOWEST P
%
%   [C,ia,ic] = unique(A)
%   C = A(ia) and A = C(ic).



% SORT VARIANTS BY FISHERS P-VALUE
[J , I] = sortrows(ASYMX.FISHPS);
ASYMX   = ASYMX(I,:);
ASYCASE = ASYCASE(I);
ASYCTRL = ASYCTRL(I);
ASYMX.VID = (1:size(ASYMX,1))';



% ONLY INCLUDE FIRST VARIANT FOUND FOR EACH GENE
[C,ia,ic] = unique(string(ASYMX.GENE));

ASYMX   = ASYMX(  ia , :);
ASYCASE = ASYCASE(ia);
ASYCTRL = ASYCTRL(ia);
ASYMX.VID = (1:size(ASYMX,1))';



% SORT VARIANTS BY FISHERS P-VALUE
[J , I] = sortrows(ASYMX.FISHPS);
ASYMX   = ASYMX(I,:);
ASYCASE = ASYCASE(I);
ASYCTRL = ASYCTRL(I);
ASYMX.VID = (1:size(ASYMX,1))';

% CLEAN UP WORKSPACE
clearvars -except ADMX SNPCASE SNPCTRL PHE CASEID CTRLID CASEMX CTRLMX IDVX...
ASYMX ASYCASE ASYCTRL




%% CHECK CASE VS. CTRL VARIANT COUNTS
%{
clc;

TOTALLOCI = size(ADMX,1);

% PROPORTION OF VARIANT LOCI WITH MORE CASE THAN CTRL
ADMX.MORECASE = ADMX.CASEALTS > ADMX.CTRLALTS;
MORECASE = ADMX.MORECASE;


fprintf('\nProportion of loci with CASE > CTRL: % 0.2f \n\n',  ...
    sum(MORECASE) / TOTALLOCI)



% HOW MANY TOTAL CASE AND CTRL VARIANTS ARE THERE?
SUMCASE = sum(ADMX.CASEALTS);   % TOTAL CASE VARIANTS
SUMCTRL = sum(ADMX.CTRLALTS);   % TOTAL CTRL VARIANTS

fprintf('\nTotal CASE ALT: % 0.0f \n\n',  SUMCASE)
fprintf('\nTotal CTRL ALT: % 0.0f \n\n',  SUMCTRL)


% WHAT IS THE DIFFERENCE BETWEEN THE GROUPS?
DIFF_CASECTRL = SUMCASE - SUMCTRL;
RATIO_CASECTRL = SUMCASE / SUMCTRL;

fprintf('\nCASE - CTRL ALTS: % 0.0f \n\n',  DIFF_CASECTRL)
fprintf('\nCASE:CTRL ALTS: % 0.3f \n\n',  RATIO_CASECTRL)



% close all
% fh1=figure('Units','normalized','OuterPosition',[.01 .05 .95 .6],'Color','w','MenuBar','none');
% t = uitable(fh1,'Data',[PHE.Properties.VariableNames; table2cell(PHE(1:25,:))],...
% 'Units','normalized','Position',[.01 .01 .98 .95]);
 



%% CHECK CASE VS. CTRL VARIANT COUNTS

clc;
TOTALLOCI = size(ASYMX,1);

% PROPORTION OF VARIANT LOCI WITH MORE CASE THAN CTRL
ASYMX.MORECASE = ASYMX.CASEALTS > ASYMX.CTRLALTS;
MORECASE = ASYMX.MORECASE;


fprintf('\nProportion of loci with CASE > CTRL: % 0.2f \n\n',  ...
    sum(MORECASE) / TOTALLOCI)



% HOW MANY TOTAL CASE AND CTRL VARIANTS ARE THERE?
SUMCASE = sum(ASYMX.CASEALTS);   % TOTAL CASE VARIANTS
SUMCTRL = sum(ASYMX.CTRLALTS);   % TOTAL CTRL VARIANTS

fprintf('\nTotal CASE ALT: % 0.0f \n\n',  SUMCASE)
fprintf('\nTotal CTRL ALT: % 0.0f \n\n',  SUMCTRL)


% WHAT IS THE DIFFERENCE BETWEEN THE GROUPS?
DIFF_CASECTRL = SUMCASE - SUMCTRL;
RATIO_CASECTRL = SUMCASE / SUMCTRL;

fprintf('\nCASE - CTRL ALTS: % 0.0f \n\n',  DIFF_CASECTRL)
fprintf('\nCASE:CTRL ALTS: % 0.3f \n\n',  RATIO_CASECTRL)

%}



%% MAKE  SQUARE  NN VARIANT MATRIX
disp('MAKING NN-SHAPED VARIANT MATRIX')


[ADNN, caMX, coMX] = makeNNMX(ASYMX,ASYCASE,ASYCTRL,CASEID,CTRLID);


clearvars -except ADMX SNPCASE SNPCTRL PHE CASEID CTRLID CASEMX CTRLMX IDVX...
ASYMX ASYCASE ASYCTRL ADNN caMX coMX







%% SAVE DATASET FOR GENOS_COVAR_ANALYSIS SCRIPT


AYX.ADMX    = ADMX;
AYX.SNPCASE = SNPCASE;
AYX.SNPCTRL = SNPCTRL;
AYX.ADNN    = ADNN;
AYX.caMX    = caMX;
AYX.coMX    = coMX;
AYX.CASEID  = CASEID;
AYX.CTRLID  = CTRLID;
AYX.PHE     = PHE;
AYX.IDVX    = IDVX;

save('GENOS_AYX.mat','AYX');




% EYX.ADMX    = ADMX;
% EYX.SNPCASE = SNPCASE;
% EYX.SNPCTRL = SNPCTRL;
% EYX.ADNN    = ADNN;
% EYX.caMX    = caMX;
% EYX.coMX    = coMX;
% EYX.CASEID  = CASEID;
% EYX.CTRLID  = CTRLID;
% EYX.PHE     = PHE;
% EYX.IDVX    = IDVX;
% 
% save('GENOS_EYX.mat','EYX');


